#Bernard Ladenthin
#2013-05-01
#bernard.ladenthin@gmail.com
VERSION = 1.0

prefix=/usr

install:
	install -m 0755 snowman-py-avconv.py $(prefix)/bin
	install -m 0755 snowman-py-avconv.py $(prefix)/local/bin

.PHONY: clean install

