#Bernard Ladenthin
#2013-05-01
VERSION = 1.0

prefix=/usr

install:
	install -m 0755 snowman-py-ffmpeg.py $(prefix)/bin
	install -m 0755 snowman-py-ffmpeg.py $(prefix)/local/bin

.PHONY: clean install

